version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: my_postgres_db_persistant
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: my_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin  
    networks:
      - my_network
    restart: unless-stopped
    depends_on:
      - postgres

volumes:
  postgres_data:
    external: true
  pgadmin_data:

networks:
  my_network:
    driver: bridge
